### ISSUE TITLE
Robadizimos los C scripts.

### ISSUE THREAD

**Issue by Suavesito-Olimpiada** [VentGrey/dotfiles#1]
:100: / :100:

**Comment by VentGrey** [comment]
Les dejé el header de licencia pa no hacer otro cagadero como el que hice en el README de Epitaph. Los únicos que no tienen header son los escrotos por mi / el de memoria que refactorizaste.

**Comment by Suavesito-Olimpiada** [comment]
Voy a portar el de batería de Rust a C.
